services: 
  - docker
before_install:
  - docker build -t arver1/frontend:latest -f test/Dockerfile.dev .
script:
  - docker run arver1/frontend:latest npm run test -- --watchAll=false --coverage
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-642769327745"
  busket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
